spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/interview_test?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    name: interview_test
    username: root
    password: zhangjiaming
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

